name: Safe Sync Check

on:
  pull_request:
    branches: [development]

jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Confirming this branch is up-to-date 👍
        run: echo "This dummy check exists only to ensure pull before merge"